version: "3.9"

services:
  web:
    build: .
    image: to-do-image
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo?createDatabaseIfNotExist=true
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - todo-app-net
    expose:
      - "8080"

  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - todo-mysql-db:/var/lib/mysql
    healthcheck:
      test: /usr/bin/mysql --user=root --password=root --execute "SELECT 1"
      interval: 2s
      timeout: 20s
      retries: 10
    restart: on-failure
    networks:
      - todo-app-net
    expose:
      - "3306"

networks:
  todo-app-net:

volumes:
  todo-mysql-db: