version: "3.9"

services:
  web:
    image: to-do-image
    ports:
      - "48658:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo?createDatabaseIfNotExist=true
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "48659:3306"
    volumes:
      - todo-mysql-db:/var/lib/mysql
    healthcheck:
      test: /usr/bin/mysql --user=root --password=root --execute "SELECT 1"
      interval: 2s
      timeout: 20s
      retries: 10
    restart: on-failure

volumes:
  todo-mysql-db: