version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - todo-mysql-db:/var/lib/mysql
    healthcheck:
      test: /usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\"
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  todo-mysql-db: